const txtAnim = document.querySelector('h1');

new Typewriter(txtAnim, {
    deleteSpeed: 30
})
.changeDelay(30)
.typeString('Hello moi c\'est omar, ')
.pauseFor(400)
.typeString('Dev Full-Stack junior')
.pauseFor(300)
.deleteChars(20)
.typeString('ev <span style="color: #FC7607"> html 5 </span>-<span style="color: #116DF1"> css 3 </span> !')
.pauseFor(500)
.deleteChars(8)
// .typeString('<span style="color: #116DF1"> css</span> !')
// .pauseFor(500)
.deleteChars(10)
.typeString('<span style="color: #EA1D0C"> javascript</span> !')
.pauseFor(500)
.deleteChars(14)
.typeString('<span style="color: #411084"> bootstrap</span> !')
.pauseFor(500)
.deleteChars(13)
.typeString('<span style="color: #F904B2"> jquery</span>!')
.pauseFor(500)
.deleteChars(8)
.typeString('<span style="color: #07F335"> M.E.R.N</span> !')
.pauseFor(500)
.deleteChars(9)
// .typeString('<span style="color: #0AEFF5"> react</span> !')
// .pauseFor(500)
// .deleteChars(9)
// .typeString('<span style="color: #F904B2"> express.js</span> !')
// .pauseFor(500)
// .deleteChars(14)
// .typeString('<span style="color: #127126"> mango.db</span> !')
// .pauseFor(500)
// .deleteChars(10)
.typeString('<span style="color: #4E66EE"> my.sql</span> !')
.pauseFor(500)
.deleteChars(10)
.typeString('<span style="color: #A52C19"> git</span> !')
.pauseFor(500)
.deleteChars(6)
.typeString('<span style="color: #8D8EBE"> php</span> !')
.pauseFor(500)
.deleteChars(11)
.typeString(' un super dev quoi !')
.start()



